"""initial schema: users, job_openings, applications, application_interviewers, application_history_entries

Revision ID: 00efbc95d414
Revises: 
Create Date: 2026-08-31 02:27:28.280961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00efbc95d414'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('RECRUITER', 'INTERVIEWER', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('job_openings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='opening_status'), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_openings_archived'), 'job_openings', ['archived'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_opening_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=255), nullable=False),
    sa.Column('candidate_email', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('current_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=False),
    sa.Column('rejected_from_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('stage_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stall_dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stall_dismissed_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['job_opening_id'], ['job_openings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_candidate_email'), 'applications', ['candidate_email'], unique=False)
    op.create_index(op.f('ix_applications_candidate_name'), 'applications', ['candidate_name'], unique=False)
    op.create_index(op.f('ix_applications_current_stage'), 'applications', ['current_stage'], unique=False)
    op.create_index(op.f('ix_applications_job_opening_id'), 'applications', ['job_opening_id'], unique=False)
    op.create_index('ix_applications_opening_stage', 'applications', ['job_opening_id', 'current_stage'], unique=False)
    op.create_index(op.f('ix_applications_stage_changed_at'), 'applications', ['stage_changed_at'], unique=False)
    op.create_table('application_history_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATED', 'STAGE_CHANGE', 'REJECTED', 'REINSTATED', 'FEEDBACK', name='history_event_type'), nullable=False),
    sa.Column('old_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('new_stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER', 'HIRED', 'REJECTED', name='application_stage'), nullable=True),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_history_entries_application_id'), 'application_history_entries', ['application_id'], unique=False)
    op.create_index(op.f('ix_application_history_entries_created_at'), 'application_history_entries', ['created_at'], unique=False)
    op.create_index('ix_history_application_created', 'application_history_entries', ['application_id', 'created_at'], unique=False)
    op.create_table('application_interviewers',
    sa.Column('application_id', sa.Integer(), nullable=False),
    sa.Column('interviewer_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('application_id', 'interviewer_id')
    )
    op.create_index(op.f('ix_application_interviewers_interviewer_id'), 'application_interviewers', ['interviewer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_interviewers_interviewer_id'), table_name='application_interviewers')
    op.drop_table('application_interviewers')
    op.drop_index('ix_history_application_created', table_name='application_history_entries')
    op.drop_index(op.f('ix_application_history_entries_created_at'), table_name='application_history_entries')
    op.drop_index(op.f('ix_application_history_entries_application_id'), table_name='application_history_entries')
    op.drop_table('application_history_entries')
    op.drop_index(op.f('ix_applications_stage_changed_at'), table_name='applications')
    op.drop_index('ix_applications_opening_stage', table_name='applications')
    op.drop_index(op.f('ix_applications_job_opening_id'), table_name='applications')
    op.drop_index(op.f('ix_applications_current_stage'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_name'), table_name='applications')
    op.drop_index(op.f('ix_applications_candidate_email'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_job_openings_archived'), table_name='job_openings')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
